version: 2

updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "gradle"
    groups:
      kotlin-dependencies:
        patterns:
          - "org.jetbrains.kotlin*"
      androidx-dependencies:
        patterns:
          - "androidx.*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "github-actions"
